services:
  {{ container_name }}:
    image: postgres:16-alpine3.20
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./{{ container_name }}:/var/lib/postgresql/data
    networks:
      - topicdb-cluster

volumes:
  {{ container_name }}:
